test failed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,12 +14,12 @@ jobs:
       - name: Look
         run: ls -al
       - name: Force Fail
-        run: exit 1   # 故意失败
+        run: exit 1   # 让 job 失败
 
   unstash:
     runs-on: ubuntu-latest
     needs: [checkout-and-stash]
-    if: always()                # 无论前一个 job 成功还是失败都会运行
+    if: failure()                # 仅在前一个 job 失败时才运行
     steps:
-      - name: Check
-        run: ls -al
+      - name: Only run if previous failed
+        run: echo "Previous job failed, running recovery steps."
